version: '3.3'

services:
  nfs:
    image: nfs
    container_name: nfs
    networks:
      xmsnet:
    ports:
      - "2049:2049/tcp"
    restart: always
    volumes:
      - ./ganesha.conf:/etc/ganesha/ganesha.conf
      - /mnt/dane:/mnt/dane
    command: './start.sh'
    privileged: true

networks:
  xmsnet:
    external:
      name: xmsnet
